name: ez
description: EZOFIS V5

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  get: 4.2.4
  flutter_screenutil: ^5.5.3+2
  get_storage: ^2.0.3
  connectivity_plus: ^2.3.4
  data_connection_checker: ^0.3.4
  permission_handler: ^9.2.0
  http: ^0.13.3
  catcher: ^0.7.0
  material_design_icons_flutter: ^6.0.7096
  shared_preferences: ^2.1.1
  flutter_simple_treeview: ^3.0.2
  tree_view: ^0.0.5
  dynamic_treeview: 1.0.0+2
  json_serializable: ^6.3.1
  basic_utils: ^5.5.4
  animated_floating_buttons: ^0.0.2
  #flutter_boom_menu: ^1.0.1
  #simple_speed_dial: ^0.1.7
  filesize: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  json_annotation: ^4.6.0

  path_provider: ^2.0.11
  url_launcher: ^6.1.5
  encrypt: ^5.0.1
  badges: ^3.1.1
  flutter_otp_text_field: ^1.1.0+2
  #local_auth: ^1.1.0
  carousel_slider: ^4.2.1
  another_stepper: ^1.2.2
  stepper_list_view: ^0.0.1
  shimmer: ^3.0.0
  ffi: ^2.0.0
  sticky_headers: ^0.3.0+2
  number_inc_dec: ^0.8.0
  #flutter_datetime_picker: ^1.5.1
  #date_time_picker: ^2.1.0
  #datetime_picker_formfield_new: ^2.1.0
  #flutter_staggered_grid_view: ^0.6.0
  dynamic_height_grid_view: ^0.0.4
  #expandable_search_bar: ^0.0.2
  #colorful_progress_indicators: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^0.1.3
  #build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/files/
    - assets/images/logo/ezofis/
    - assets/images/logo/social/
    - assets/images/logo/user/
    - assets/images/background/
    - assets/images/user/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit-Light.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit-Thin.ttf
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon/android.png"
  image_path_ios: "assets/images/launcher_icon/ios.png"
  remove_alpha_ios: true
